spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer

logging:
  level:
    org.hibernate:
      sql: debug
      type.descriptor.jdbc.BasicBinder: trace
