spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
