version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: coupon_example
    ports:
    - '3306:3306'
    volumes:
    - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
